// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PigFarmManagement.Server.Infrastructure.Data;

#nullable disable

namespace PigFarmManagement.Server.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PigFarmDbContext))]
    partial class PigFarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zipcode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.DepositEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PigPenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PigPenId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.FeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProductCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProductName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FeedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceReferenceCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PigPenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("UnmappedProduct")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PigPenId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.FeedFormulaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConsumeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ExternalId");

                    b.ToTable("FeedFormulas");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.HarvestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PigCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PigPenId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePricePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PigPenId");

                    b.ToTable("Harvests");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActHarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositPerPig")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EstimatedHarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Investment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCalculationLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PenCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PigQty")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProfitLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedBrand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PenCode")
                        .IsUnique();

                    b.ToTable("PigPens");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenFormulaAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AssignedBagPerPig")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("AssignedPigQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AssignedTotalBags")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OriginalFormulaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PigPenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalFormulaId");

                    b.HasIndex("PigPenId");

                    b.ToTable("PigPenFormulaAssignments");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.DepositEntity", b =>
                {
                    b.HasOne("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", "PigPen")
                        .WithMany("Deposits")
                        .HasForeignKey("PigPenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PigPen");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.FeedEntity", b =>
                {
                    b.HasOne("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", "PigPen")
                        .WithMany("Feeds")
                        .HasForeignKey("PigPenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PigPen");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.HarvestEntity", b =>
                {
                    b.HasOne("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", "PigPen")
                        .WithMany("Harvests")
                        .HasForeignKey("PigPenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PigPen");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", b =>
                {
                    b.HasOne("PigFarmManagement.Server.Infrastructure.Data.Entities.CustomerEntity", "Customer")
                        .WithMany("PigPens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenFormulaAssignmentEntity", b =>
                {
                    b.HasOne("PigFarmManagement.Server.Infrastructure.Data.Entities.FeedFormulaEntity", "OriginalFormula")
                        .WithMany()
                        .HasForeignKey("OriginalFormulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", "PigPen")
                        .WithMany("FormulaAssignments")
                        .HasForeignKey("PigPenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalFormula");

                    b.Navigation("PigPen");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.CustomerEntity", b =>
                {
                    b.Navigation("PigPens");
                });

            modelBuilder.Entity("PigFarmManagement.Server.Infrastructure.Data.Entities.PigPenEntity", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("Feeds");

                    b.Navigation("FormulaAssignments");

                    b.Navigation("Harvests");
                });
#pragma warning restore 612, 618
        }
    }
}
